<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'BasicException' => 'common/exceptions/BasicException.php',
    'BasicModel' => 'common/BasicModel.php',
    'CommonExceptionsTestCase' => 'common/exceptions/__tests__/CommonExceptionsTestCase.php',
    'Language' => 'common/Language.php',
    'LanguageException' => 'common/exceptions/LanguageException.php',
    'SecurityLevel' => 'common/SecurityLevel.php',
    'SecurityLevelException' => 'common/exceptions/SecurityLevelException.php',
    'Wiki' => 'wiki/Wiki.php',
    'WikiException' => 'wiki/WikiException.php',
    'WikiExceptionTestCase' => 'wiki/__tests__/WikiExceptionTestCase.php',
    'WikiModel' => 'wiki/WikiModel.php',
    'WikiParameterException' => 'wiki/WikiParameterException.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'BasicException' => 'Exception',
    'CommonExceptionsTestCase' => 'ArcanistPhutilTestCase',
    'LanguageException' => 'BasicException',
    'SecurityLevelException' => 'BasicException',
    'WikiException' => 'Exception',
    'WikiExceptionTestCase' => 'ArcanistPhutilTestCase',
    'WikiModel' => 'BasicModel',
    'WikiParameterException' => 'WikiException',
  ),
));
