<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'BasicException' => 'common/BasicException.php',
    'DatabaseException' => 'common/database/DatabaseException.php',
    'DatabaseExceptionTestCase' => 'common/database/__tests__/DatabaseExceptionTestCase.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'BasicException' => 'Exception',
    'DatabaseException' => 'BasicException',
    'DatabaseExceptionTestCase' => 'ArcanistPhutilTestCase',
  ),
));
