<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 * @generated
 * @phutil-library-version 2
 */

phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' =>
  array(
    'BasicException' => 'common/exceptions/BasicException.php',
    'BasicModel' => 'common/BasicModel.php',
    'CommonExceptionsTestCase' => 'common/exceptions/__tests__/CommonExceptionsTestCase.php',
    'Configuration' => 'config/Configuration.php',
    'ConfigurationException' => 'config/ConfigurationException.php',
    'ConfigurationLoadingTestCase' => 'config/__tests__/ConfigurationLoadingTestCase.php',
    'InfoarenaEnvironment' => 'env/InfoarenaEnvironment.php',
    'InfoarenaLintEngine' => 'lint/engine/InfoarenaLintEngine.php',
    'Language' => 'common/Language.php',
    'LanguageException' => 'common/exceptions/LanguageException.php',
    'SpecializedLog' => 'log/SpecializedLog.php',
    'SpecializedLogException' => 'log/SpecializedLogException.php',
    'SpecializedLogTestCase' => 'log/__tests__/SpecializedLogTestCase.php',
    'User' => 'user/User.php',
    'UserException' => 'user/UserException.php',
    'UserParameterException' => 'user/UserParameterException.php',
    'UserSecurityLevel' => 'user/UserSecurityLevel.php',
    'UserSecurityLevelException' => 'user/UserSecurityLevelException.php',
    'Wiki' => 'wiki/Wiki.php',
    'WikiException' => 'wiki/WikiException.php',
    'WikiExceptionTestCase' => 'wiki/__tests__/WikiExceptionTestCase.php',
    'WikiModel' => 'wiki/WikiModel.php',
    'WikiParameterException' => 'wiki/WikiParameterException.php',
    'WikiSecurityLevel' => 'wiki/WikiSecurityLevel.php',
    'WikiSecurityLevelException' => 'wiki/WikiSecurityLevelException.php',
  ),
  'function' =>
  array(
  ),
  'xmap' =>
  array(
    'BasicException' => 'Exception',
    'CommonExceptionsTestCase' => 'ArcanistPhutilTestCase',
    'ConfigurationException' => 'BasicException',
    'ConfigurationLoadingTestCase' => 'ArcanistPhutilTestCase',
    'InfoarenaLintEngine' => 'PhutilLintEngine',
    'LanguageException' => 'BasicException',
    'SpecializedLogException' => 'BasicException',
    'SpecializedLogTestCase' => 'ArcanistPhutilTestCase',
    'UserException' => 'BasicException',
    'UserParameterException' => 'UserException',
    'UserSecurityLevelException' => 'UserException',
    'WikiException' => 'BasicException',
    'WikiExceptionTestCase' => 'ArcanistPhutilTestCase',
    'WikiModel' => 'BasicModel',
    'WikiParameterException' => 'WikiException',
    'WikiSecurityLevelException' => 'BasicException',
  ),
));
